import type { RegistryEntry } from './models';

export const MOCK_REGISTRY: RegistryEntry[] = [
  {
    id: 'reg-usdc',
    submissionId: 'sub-usdc',
    organizationId: 'org-circle',
    organizationName: 'Circle Internet Financial',
    name: 'USD Coin',
    ticker: 'USDC',
    network: 'solana',
    contractAddress: '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU',
    reserveDisclosure: 'https://www.circle.com/en/transparency',
    attestationUrl: 'https://www.circle.com/en/transparency',
    publicationStatus: 'published',
    publishedAt: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'reg-eurc',
    submissionId: 'sub-eurc',
    organizationId: 'org-circle',
    organizationName: 'Circle Internet Financial',
    name: 'Euro Coin',
    ticker: 'EURC',
    network: 'solana',
    contractAddress: 'HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr',
    reserveDisclosure: 'https://www.circle.com/en/transparency',
    attestationUrl: 'https://www.circle.com/en/transparency',
    publicationStatus: 'published',
    publishedAt: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'reg-cghs',
    submissionId: 'sub-cghs',
    organizationId: 'org-ghanacoin',
    organizationName: 'GhanaCoin Foundation',
    name: 'Cedi Stablecoin',
    ticker: 'cGHS',
    network: 'solana',
    contractAddress: 'demo_cGHS_mint_address_placeholder',
    reserveDisclosure: 'Reserve backed by GHS deposits at licensed banks',
    attestationUrl: null,
    publicationStatus: 'published',
    publishedAt: '2026-09-15T00:00:00Z',
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'reg-cxof',
    submissionId: 'sub-cxof',
    organizationId: 'org-westafrica-digital',
    organizationName: 'West Africa Digital Finance',
    name: 'CFA Franc Stablecoin',
    ticker: 'cXOF',
    network: 'solana',
    contractAddress: 'demo_cXOF_mint_address_placeholder',
    reserveDisclosure: 'Reserve backed by XOF deposits at BCEAO-licensed institutions',
    attestationUrl: null,
    publicationStatus: 'published',
    publishedAt: '2026-09-20T00:00:00Z',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'reg-cngn',
    submissionId: 'sub-cngn',
    organizationId: 'org-nairabridge',
    organizationName: 'NairaBridge Ltd',
    name: 'Naira Stablecoin',
    ticker: 'cNGN',
    network: 'solana',
    contractAddress: 'demo_cNGN_mint_address_placeholder',
    reserveDisclosure: 'Reserve backed by NGN deposits at CBN-licensed banks',
    attestationUrl: null,
    publicationStatus: 'published',
    publishedAt: '2026-09-25T00:00:00Z',
    createdAt: '2026-09-25T00:00:00Z',
  },
  {
    id: 'reg-ckes',
    submissionId: 'sub-ckes',
    organizationId: 'org-kenyastable',
    organizationName: 'KenyaStable Inc',
    name: 'Kenyan Shilling Stablecoin',
    ticker: 'cKES',
    network: 'solana',
    contractAddress: 'demo_cKES_mint_address_placeholder',
    reserveDisclosure: 'Reserve backed by KES deposits at CBK-licensed institutions',
    attestationUrl: null,
    publicationStatus: 'published',
    publishedAt: '2026-10-01T00:00:00Z',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'reg-ctry',
    submissionId: 'sub-ctry',
    organizationId: 'org-turkstable',
    organizationName: 'TurkStable A.S.',
    name: 'Turkish Lira Stablecoin',
    ticker: 'cTRY',
    network: 'solana',
    contractAddress: 'demo_cTRY_mint_address_placeholder',
    reserveDisclosure: 'Reserve backed by TRY deposits at BDDK-licensed banks',
    attestationUrl: null,
    publicationStatus: 'published',
    publishedAt: '2026-10-05T00:00:00Z',
    createdAt: '2026-10-05T00:00:00Z',
  },
];

export const CURRENCY_SYMBOLS: Record<string, string> = {
  USDC: '$',
  EURC: '€',
  cGHS: '₵',
  cXOF: 'CFA ',
  cNGN: '₦',
  cKES: 'KSh ',
  cTRY: '₺',
};

export function getCurrencySymbol(ticker: string): string {
  return CURRENCY_SYMBOLS[ticker] ?? ticker + ' ';
}
