packages:
  - "apps/*"
  - "packages/*"
overrides:
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5
  react-native-svg: 15.12.1
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
