import { ApiProperty } from '@nestjs/swagger';
import { IsString, MinLength } from 'class-validator';

export class SignOfframpUrlDto {
  @ApiProperty({
    description: 'Unsigned MoonPay widget URL generated by the React Native SDK.',
    example: 'https://sell-sandbox.moonpay.com?apiKey=pk_test&baseCurrencyCode=usdc_sol',
  })
  @IsString()
  @MinLength(1)
  url: string;
}
