"use client";
import { useEffect, useState } from "react";
import type { MerchantProduct, MerchantProductAnalytics } from "@repo/shared";
import { X } from "lucide-react";
import { Alert } from "@repo/ui/alert";
import { Button } from "@repo/ui/button";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { Money } from "@repo/ui/money";
import { portalApi } from "@/lib/client/api";

export function ProductAnalyticsDrawer({ product, open, onOpenChange }: { product: MerchantProduct | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [data, setData] = useState<MerchantProductAnalytics | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!open || !product) return; setData(null); setError(""); void portalApi<MerchantProductAnalytics>(`me/products/${product.id}/analytics?period=30d`).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Product analytics could not be loaded.")); }, [open, product]);
  return <Drawer direction="right" open={open} onOpenChange={onOpenChange}><DrawerContent className="h-dvh w-full overflow-hidden rounded-none sm:max-w-md"><DrawerHeader className="relative border-b border-slate-200 pr-16"><DrawerTitle>{product?.name ?? "Product analytics"}</DrawerTitle><DrawerDescription>Recorded sales for the last 30 days. Custom sales stay unassigned until linked to a product.</DrawerDescription><DrawerClose asChild><Button type="button" variant="ghost" size="icon" aria-label="Close product analytics" className="absolute right-3 top-3"><X/></Button></DrawerClose></DrawerHeader><div className="grid gap-4 overflow-y-auto p-6">{error ? <Alert className="border-red-200 bg-red-50 text-red-800">{error}</Alert> : null}{data ? <><Metric label="Quantity sold" value={data.quantitySold}/><Metric label="Recorded revenue" value={<Money value={data.revenue}/>}/><Metric label="Digital / cash units" value={`${data.digitalQuantity} / ${data.cashQuantity}`}/><Metric label="Average daily units" value={data.averageDailyQuantity.toFixed(1)}/><Metric label="Peak selling hour" value={data.peakSellingHour === null ? "No recorded sales" : `${String(data.peakSellingHour).padStart(2, "0")}:00`}/><div className="rounded-lg border border-slate-200 p-4 text-sm text-slate-600"><p className="font-medium text-slate-950">Stock now</p><p className="mt-1">{data.availableQuantity} available · {data.onHandQuantity} on hand · {data.reservedQuantity} reserved</p><p className="mt-3 text-xs">{data.stockTrackingNote}</p></div><div><p className="text-sm font-medium text-slate-950">Stock movements</p>{data.stockMovements.length ? <div className="mt-2 divide-y divide-slate-100 rounded-lg border border-slate-200">{data.stockMovements.map((movement, index) => <div className="flex items-center justify-between gap-3 p-3 text-xs" key={`${movement.occurredAt}-${index}`}><span className="capitalize text-slate-600">{movement.kind.replaceAll("_", " ")}</span><span className={movement.onHandChange > 0 ? "text-emerald-700" : movement.onHandChange < 0 ? "text-rose-700" : "text-slate-500"}>{movement.onHandChange === 0 ? "No on-hand change" : `${movement.onHandChange > 0 ? "+" : ""}${movement.onHandChange} on hand`}</span></div>)}</div> : <p className="mt-2 text-xs text-slate-500">No post-upgrade movements yet.</p>}</div></> : !error ? <p className="text-sm text-slate-500">Loading product analytics…</p> : null}</div></DrawerContent></Drawer>;
}
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="border-b border-slate-100 pb-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold text-slate-950">{value}</p></div>; }
